"""
Collect the inputs of Tutorial K from the global quadtree experiment.

The forecasts (M7.45+ rates per year on multi-resolution quadtree grids) and the
gCMT catalogue come from a local copy of the global experiment. They are copied
here but not tracked by git (see the repository .gitignore), because several of
the forecasts are unpublished research output.

Usage::

    python prepare.py --source /path/to/globalExperiment [--grids N50L11 SN10L11 ...]

Every model is set up on every selected grid (all eight by default), named
``<MODEL>=<GRID>`` as in the global experiment, and ``models.yml`` is rewritten
to match. The source directory is only read.
"""

import argparse
import csv
import datetime
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

MODELS = {
    "GEAR1": "Global Earthquake Activity Rate model (published GEFE forecast, benchmark)",
    "KJSS": "Kagan-Jackson smoothed seismicity (published GEFE forecast)",
    "SHIFT2F_GSRM": "SHIFT model on the GSRM strain rates (published GEFE forecast)",
    "TEAM": "TEAM ensemble (published GEFE forecast)",
    "WHEEL": "WHEEL ensemble (published GEFE forecast)",
    "EEPASfull": "EEPAS mixed with PPE, (1 - mu) EEPAS + mu PPE",
    "PPE": "Proximity to Past Earthquakes",
    "SUP": "Spatially uniform baseline",
    "GSSGSRM": "Hybrid of SUP and the GSRM strain rates",
}
GRIDS = ["N10L11", "N25L11", "N50L11", "N100L11", "SN10L11", "SN25L11", "SN50L11", "SN100L11"]

FORECASTS = Path("gefe-quadtree_results_2023-03", "regen", "m745_models")
CATALOG = Path("eepasModel", "run", "gcmt_M595_1976_2022.dat")


def convert_gcmt(source: Path, target: Path) -> int:
    """gCMT table (yr mo dy hr mn sec lat lon depth Mw) -> pyCSEP ASCII catalogue."""
    rows = 0
    with open(source) as f_in, open(target, "w", newline="") as f_out:
        writer = csv.writer(f_out)
        writer.writerow(["lon", "lat", "mag", "time_string", "depth", "catalog_id", "event_id"])
        for line in f_in:
            fields = line.split()
            if len(fields) < 10:
                continue
            year, month, day, hour, minute = (int(v) for v in fields[:5])
            seconds = float(fields[5])
            lat, lon, depth, mag = (float(v) for v in fields[6:10])
            time = datetime.datetime(year, month, day, hour, minute) + datetime.timedelta(
                seconds=seconds
            )
            event_id = f"gcmt{time:%Y%m%d%H%M%S}"
            writer.writerow(
                [lon, lat, mag, time.strftime("%Y-%m-%dT%H:%M:%S.%f"), depth, -1, event_id]
            )
            rows += 1
    return rows


def write_models_yml(grids) -> None:
    lines = [
        "# Generated by prepare.py: every model on every grid, named <MODEL>=<GRID>.",
        "# Rates are expected M7.45+ events per year (forecast_unit: 1).",
    ]
    for grid in grids:
        lines.append(f"# Quadtree grid {grid}")
        for model, description in MODELS.items():
            lines += [
                f"- {model}={grid}:",
                f"    path: models/{model}={grid}.csv",
                "    forecast_unit: 1",
                f"    description: {description}",
            ]
    (HERE / "models.yml").write_text("\n".join(lines) + "\n")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--source", required=True, type=Path, help="global experiment directory"
    )
    parser.add_argument(
        "--grids",
        nargs="+",
        default=GRIDS,
        choices=GRIDS,
        help="quadtree grids (default: all)",
    )
    args = parser.parse_args(argv)

    source = args.source.expanduser().resolve()
    wanted = [(m, g) for g in args.grids for m in MODELS]
    missing = [source / CATALOG] if not (source / CATALOG).is_file() else []
    missing += [
        source / FORECASTS / f"{m}={g}.csv"
        for m, g in wanted
        if not (source / FORECASTS / f"{m}={g}.csv").is_file()
    ]
    if missing:
        listing = "\n  ".join(str(p) for p in missing)
        print(f"Missing input files:\n  {listing}", file=sys.stderr)
        return 1

    models_dir = HERE / "models"
    models_dir.mkdir(exist_ok=True)
    for model, grid in wanted:
        name = f"{model}={grid}.csv"
        shutil.copyfile(source / FORECASTS / name, models_dir / name)
    write_models_yml(args.grids)

    events = convert_gcmt(source / CATALOG, HERE / "catalog.csv")
    print(
        f"Copied {len(MODELS)} models on {len(args.grids)} grid(s) "
        f"({', '.join(args.grids)}) and {events} gCMT events (M5.95+)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
